/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    container: {
      center: true,
      padding: { DEFAULT: "1rem", sm: "1.5rem", lg: "2rem" },
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        gold: {
          50:  "#fdfbf0",
          100: "#faf4d3",
          200: "#f4e79e",
          300: "#edd363",
          400: "#E8C547",
          500: "#C9A227",
          600: "#A67C00",
          700: "#7d5c00",
          800: "#5a4200",
          900: "#3a2b00",
        },
        teal: {
          50:  "#f0f9fa",
          100: "#d9f0f1",
          200: "#b0e1e4",
          300: "#7DC4C8",
          400: "#5AAFB3",
          500: "#4E9FA3",
          600: "#3A7F83",
          700: "#2c6163",
          800: "#1f4648",
          900: "#122b2d",
        },
        border: "hsl(var(--border))",
        input:  "hsl(var(--input))",
        ring:   "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
      },
      fontFamily: {
        sans:    ["Inter", "system-ui", "sans-serif"],
        heading: ["Poppins", "sans-serif"],
        display: ['"Plus Jakarta Sans"', "sans-serif"],
      },
      backgroundImage: {
        "gradient-gold":   "linear-gradient(135deg, #E8C547 0%, #C9A227 50%, #A67C00 100%)",
        "gradient-gold-h": "linear-gradient(90deg, #E8C547 0%, #C9A227 100%)",
        "gradient-teal":   "linear-gradient(135deg, #7DC4C8 0%, #4E9FA3 100%)",
        "gradient-hero":   "linear-gradient(135deg, #0d1117 0%, #122b2d 100%)",
        "hero-overlay":    "linear-gradient(to right, rgba(13,17,23,0.95) 0%, rgba(13,17,23,0.80) 55%, rgba(13,17,23,0.50) 100%)",
      },
      boxShadow: {
        "gold":       "0 4px 24px -4px rgba(201,162,39,0.45)",
        "gold-lg":    "0 12px 40px -8px rgba(201,162,39,0.5)",
        "teal":       "0 4px 24px -4px rgba(78,159,163,0.4)",
        "teal-lg":    "0 12px 40px -8px rgba(78,159,163,0.45)",
        "card":       "0 2px 16px -2px rgba(0,0,0,0.07)",
        "card-hover": "0 16px 48px -8px rgba(0,0,0,0.14)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up":   { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        float:       { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-10px)" } },
        shimmer:     { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        blob: { "0%": { transform: "translate(0,0) scale(1)" }, "33%": { transform: "translate(20px,-30px) scale(1.08)" }, "66%": { transform: "translate(-15px,15px) scale(0.93)" }, "100%": { transform: "translate(0,0) scale(1)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up":   "accordion-up 0.2s ease-out",
        float:            "float 4s ease-in-out infinite",
        "float-slow":     "float 6s ease-in-out infinite",
        shimmer:          "shimmer 2s linear infinite",
        blob:             "blob 8s infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
